### ISSUE TITLE
backport nil deref fix (#513), CVE fixes

### ISSUE THREAD

**Issue by jkh52** [kubernetes-sigs/apiserver-network-proxy#523]
We should backport the nil deref fix (https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/513).

Actively maintained kubernetes versions are 1.25, 1.26, 1.27, and 1.28 (https://kubernetes.io/releases/).

Based on recently updated https://github.com/kubernetes-sigs/apiserver-network-proxy#versioning-and-releases, here would be the relevant branch / tag mapping:

```[tasklist]
### Tasks
- [x] 1.28: Create branch release-0.28, release tag 0.28.0
- [x] 1.27: Pick to release-0.1 branch, release tag 0.1.5
- [ ] ~~1.25 and 1.26: Pick to release-0.0 branch, release tag 0.0.38~~
- [x] Publish associated images
- [x] Update konnectivity-client in k/k master
- [ ] Update konnectivity-client in k/k release-1.28
- [ ] Update konnectivity-client in k/k release-1.27
- [ ] Release tag 0.1.7 (to get https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/561)
```

Nice to also pick up relevant CVE fixes, where applicable.

EDIT: nothing is needed for 1.25 or 1.26, because the [culprit](https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/463) is not present in 0.0.37 tag or release-0.0 branch.

**Comment by jkh52** [comment]
Promote Images: https://github.com/kubernetes/k8s.io/pull/5880

**Comment by jkh52** [comment]
k/k master branch: https://github.com/kubernetes/kubernetes/pull/120836

**Comment by jkh52** [comment]
k/k release-1.28 branch: https://github.com/kubernetes/kubernetes/pull/120884

**Comment by jkh52** [comment]
k/k release-1.27 branch: https://github.com/kubernetes/kubernetes/pull/120904

**Comment by jkh52** [comment]
@elmiko the two PRs (k/k release branches 1.27 and 1.28) have stalled out, can you help poke them?

**Comment by jkh52** [comment]
The majority of this is done, let's move to more granular items going forward (likely per minor version or tag).
