### ISSUE TITLE
backport CVE fixes to supported versions

### ISSUE THREAD

**Issue by jkh52** [kubernetes-sigs/apiserver-network-proxy#537]
Create version tags for: https://github.com/kubernetes-sigs/apiserver-network-proxy/pulls?q=is%3Apr+is%3Aclosed+v0.17.0
```[tasklist]
### Tasks
- [x] Create tag 0.28.1
- [x] Create tag 0.28.2
- [x] Create tag 0.1.6
- [x] Create tag 0.1.7
- [x] Promote 0.28.1 and 0.28.2 images
- [x] Promote 0.28.3 and 0.1.6 images
- [x] Promote 0.1.7 images
- [ ] update k/k release-1.28 to 0.28.3
- [ ] update k/k release-1.27 to 0.1.7
```

**Comment by jkh52** [comment]
There are more CVE fixes in master but not release-0.28: https://github.com/kubernetes-sigs/apiserver-network-proxy/compare/release-0.28...master

We should backport and tag a 0.28.2 version. Opened https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/540

**Comment by jkh52** [comment]
Images are promoted.

Sent https://github.com/kubernetes/kubernetes/pull/122227 to use 0.28.2 in k/k master branch.

**Comment by xrstf** [comment]
I cannot find the container image for v0.1.6. They do not appear in https://explore.ggcr.dev/?repo=registry.k8s.io%2Fkas-network-proxy%2Fproxy-server nor in https://explore.ggcr.dev/?image=gcr.io%2Fk8s-staging-kas-network-proxy%2Fproxy-server. The die image release process get stuck somewhere or was the image not promoted maybe?

**Comment by jkh52** [comment]
> I cannot find the container image for v0.1.6. They do not appear in https://explore.ggcr.dev/?repo=registry.k8s.io%2Fkas-network-proxy%2Fproxy-server nor in https://explore.ggcr.dev/?image=gcr.io%2Fk8s-staging-kas-network-proxy%2Fproxy-server. The die image release process get stuck somewhere or was the image not promoted maybe?
> 
> Likewise, the image for v0.28.3 is missing as well.

Agreed, opened https://github.com/kubernetes/k8s.io/pull/6255 to promote images for 0.1.6 and 0.28.3

**Comment by xrstf** [comment]
Thanks, the images for 1.27 (v0.1.6), 1.28 (v0.28.3) and 1.29 (v0.29.0) are now available :-)

**Comment by jkh52** [comment]
Image promotion for v0.1.7: https://github.com/kubernetes/k8s.io/pull/6397
